name: build java_graalvm_ee

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 1,15 * *" 
  push:
    branches:
      - main
    paths:
      - java-graalvm/**

permissions:
  actions: read
  packages: write

concurrency:
  group: java-graalvm-ee-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build_and_push:
    name: "java_${{ matrix.tag }}_graalvm_ee"
    runs-on: ubuntu-latest
    env:
      DOCKER_CLIENT_TIMEOUT: 120
      COMPOSE_HTTP_TIMEOUT: 120
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 26

    steps:
      - name: Git checkout for Github repository workspace
        uses: actions/checkout@v4

      - name: Setup QEMU for multiarch builds
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./java-graalvm
          platforms: linux/amd64,linux/arm64
          file: ./java-graalvm/${{ matrix.tag }}/Dockerfile
          push: true
          tags: ghcr.io/donpedrotv/pterodactyl-images:java_${{ matrix.tag }}_graalvm_ee
